#!/usr/bin/env python3
"""Parse libFuzzer recommended dictionary output into a .dict file."""

import re
import sys


def octal_to_hex(m: re.Match) -> str:
    return f"\\x{int(m.group(1), 8):02x}"


def parse_recomm_dict(input_path: str, output_path: str) -> None:
    existing: list[str] = []
    existing_set: set[str] = set()
    try:
        with open(output_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if line in existing_set:
                    continue
                existing.append(line)
                existing_set.add(line)
    except FileNotFoundError:
        pass

    new_entries: list[str] = []
    with open(input_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Strip trailing comment like  # Uses: 231
            line = re.sub(r"\s*#\s*Uses:\s*\d+\s*$", "", line)
            if not line:
                continue
            # Convert octal escapes \NNN to \xHH
            line = re.sub(r"\\([0-3][0-7]{2})", octal_to_hex, line)
            if line not in existing_set:
                new_entries.append(line)
                existing_set.add(line)

    all_entries = existing + new_entries
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by libFuzzer RECOMMENDED_DICTIONARY\n")
        for entry in all_entries:
            f.write(entry + "\n")

    print(f"Wrote {len(all_entries)} entries to {output_path} ({len(new_entries)} new)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input> <output>", file=sys.stderr)
        sys.exit(1)
    parse_recomm_dict(sys.argv[1], sys.argv[2])
