name: "Address Sanitizer Check"
on:
  workflow_dispatch:

jobs:
  ASAN-CHECK:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: ["10", "11", "12", "13", "14", "15", "14t"]
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install nix
      uses: cachix/install-nix-action@v31
    - name: Setup cachix
      uses: cachix/cachix-action@v17
      with:
        name: antares0982
    - name: Run asan check
      run: |
        nix develop .#buildenv-py3${{ matrix.pyver }} -c python ./ci/linux_test.py --asan
    - name: Run asan check (lockfree)
      if: contains(matrix.pyver, 't')
      run: |
        nix develop .#buildenv-py3${{ matrix.pyver }} -c python ./ci/linux_test.py --asan --lockfree
