name: "Build Package"
on:
  workflow_dispatch:

jobs:
  RUN-TEST:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: ["13"]
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@master
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
    - name: Test Release Build
      run: |
        bash dev_tools/autopack.sh
