name: clang-format Check
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '19'
        check-path: 'src'
        exclude-regex: "dragonbox|xxhash"
