name: Code Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install nix
      uses: cachix/install-nix-action@v31
    - name: Setup cachix
      uses: cachix/cachix-action@v17
      with:
        name: antares0982
    - name: Run coverage test
      run: |
        nix develop -c bash ./dev_tools/coverage_test.sh
        nix develop .#devenv-py314t -c bash ./dev_tools/coverage_test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./_coverage/coverage.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
