name: Format Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - "src/**"
      - "CMakeLists.txt"

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install nix
      uses: cachix/install-nix-action@v31
    - name: Run format check
      run: |
        nix shell nixpkgs#clang-tools nixpkgs#cmake-format -c bash ./dev_tools/format-src.sh
        if ! git diff --exit-code; then
          echo "::error::The following files are not properly formatted:"
          git diff --name-only
          exit 1
        fi
